version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
           - .circleci
 
  deploy:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - attach_workspace:
          at: .
      - run: pip install --user --upgrade pip
      - run: pip3 install --user ansible boto boto3
      - run: echo $SSH_PRIVATE_KEY | sed 's/<CRLF>/\n/g' > test.pem
      - run: chmod 400 test.pem
      - run: export ANSIBLE_HOST_KEY_CHECKING=False
      - run: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook .circleci/ec2_deploy.yml --user ubuntu --key-file test.pem

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build