version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
 
  deploy:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - attach_workspace:
          at: .
      - run: pip3 install ansible boto boto3
      - run: echo $SSH_PRIVATE_KEY | sed 's/<CRLF>/\n/g' > test.pem
      - run: chmod 400 newkey2.pem
      - run: export ANSIBLE_HOST_KEY_CHECKING=False
      - run: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook ec2_deploy.yml --user ubuntu --key-file test.pem

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build